#! /usr/bin/env bash

echo "
  ___     _   _ _       _ _
 / __|___| |_| | | __ _(_| |_
 \\__ / -_|  _|_  _/ _\` | |  _|
 |___\\___|\\__| |_|\\__, |_|\\__|
                  |___/
    by leelsey


Set4git options
 1. Install git
 2. Configure git
 3. Setup git global ignore
 4. Install and configure git
 5. Install, configure and setup git global ignore
 0. Exit
"
read -p "Choose Set5git option: " set4gitoption
if ! [[ "$set4gitoption" =~ ^[0-5]+$ ]]; then
    echo "Please input a number between 0 and 5"
    echo "Exit"
    exit 1
fi
if [ "$set4gitoption" == "0" ]; then
    echo "Exit"
    exit 1
elif [ "$set4gitoption" == "1" ]; then
    ./git-install.sh
elif [ "$set4gitoption" == "2" ]; then
    ./git-conf.sh
elif [ "$set4gitoption" == "3" ]; then
    ./git-ignore.sh
elif [ "$set4gitoption" == "4" ]; then
    ./git-install.sh
    ./git-conf.sh
elif [ "$set4gitoption" == "5" ]; then
    ./git-install.sh
    ./git-conf.sh
    ./git-ignore.sh
fi
echo "
Finished!


Your Git Information

$(git --version)
$(git config --list)"
